[[main]]
  name = "Support"
  identifier = "support"
  weight = 40
  pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
[[main]]
  name = "Repository"
  identifier = "repository"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
  weight = 1
[[main]]
  name = "Discussions"
  identifier = "discussions"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap/discussions/new"
  weight = 2
[[main]]
  name = "Features Request"
  identifier = "feature-request"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=feature_request.md"
  weight = 3
[[main]]
  parent = "support"
  weight = 4
  [main.params]
    divider = true
